// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlylxs3SCQ9mHYO4G6POwqlinxsYHVJts',
    appId: '1:921289458579:web:cf92b5966b0f8575d51e66',
    messagingSenderId: '921289458579',
    projectId: 'chatapp-477106',
    authDomain: 'chatapp-477106.firebaseapp.com',
    storageBucket: 'chatapp-477106.firebasestorage.app',
    measurementId: 'G-Q6KB5YVMY3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwJeNo9allCa1h0bpVJ96qyZ1mUJRoz84',
    appId: '1:921289458579:android:86537d849c5dc2bad51e66',
    messagingSenderId: '921289458579',
    projectId: 'chatapp-477106',
    storageBucket: 'chatapp-477106.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkb8Oa2McMWmLhtJeNzLAC3GdpkmKoshw',
    appId: '1:921289458579:ios:6551d81e2a6c4858d51e66',
    messagingSenderId: '921289458579',
    projectId: 'chatapp-477106',
    storageBucket: 'chatapp-477106.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkb8Oa2McMWmLhtJeNzLAC3GdpkmKoshw',
    appId: '1:921289458579:ios:6551d81e2a6c4858d51e66',
    messagingSenderId: '921289458579',
    projectId: 'chatapp-477106',
    storageBucket: 'chatapp-477106.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlylxs3SCQ9mHYO4G6POwqlinxsYHVJts',
    appId: '1:921289458579:web:f8f3f1d9731d3543d51e66',
    messagingSenderId: '921289458579',
    projectId: 'chatapp-477106',
    authDomain: 'chatapp-477106.firebaseapp.com',
    storageBucket: 'chatapp-477106.firebasestorage.app',
    measurementId: 'G-CFR89SX4J8',
  );

}